from .tag_filter_node import TAG_FILTER_CLASS_MAPPINGS, TAG_FILTER_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TAG_FILTER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TAG_FILTER_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
